name: Islands
main: me.flaymed.islands.Islands
version: 0.1
author: Flaymed
depend:
  - GameCore
commands:
  leave:
    description: Leave a game.
    usage: /leave
  ore:
    description: Change ore settings
    usage: /ore
  bridges:
    description: Drop the bridges
    usage: /bridges